### ISSUE TITLE
Use WritingStats on local machine only

### ISSUE THREAD

**Issue by henningsway** [smarr/WritingStats#5]
Dear Stefan,

I'm quite interested to use your scripts locally on my linux machine, to visualize several writing projects. It should be possible to install Latex-Mk and TeXcount and then run some of the scripts from the terminal, right?
I'm note entirely sure how to approach this, so any help would be appreciated.

Great idea! ;)

**Comment by smarr** [comment]
Yes, check out the [post-receive](https://github.com/smarr/WritingStats/blob/master/status/post-receive) script. That does all the things that are relevant. It generates the files with the stats.
